services:
  traefik:
    image: traefik:v3.5
    ports:
      - "80:80"
      # Dashboard (8080) is only exposed in development via docker-compose.dev.yml
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
